# Generated by Django 4.2.3 on 2023-07-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='URL',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
