# Generated by Django 4.2.3 on 2023-07-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.genre')),
            ],
        ),
    ]
