# Generated by Django 4.2.3 on 2023-07-19 04:29

import blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_genre_url'),
        ('author', '0003_author_username'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('numberOfUsed', models.IntegerField(default=1)),
                ('numbOfClicked', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='AuthorInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='author.authorinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='Device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.device'),
        ),
        migrations.AddField(
            model_name='blog',
            name='URL',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='article',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='big_poster',
            field=models.ImageField(default=1, upload_to=blog.models.BigPosterPath),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='brif',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='descriptions',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_descriptions',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='small_poster',
            field=models.ImageField(default=1, upload_to=blog.models.SmallPosterPath),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlogReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.IntegerField(choices=[(0, 'Null'), (1, 'Inthemoment'), (2, 'Scheduled')], default=0)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('view', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('Blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'verbose_name': 'Reports',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
