# Generated by Django 4.2.3 on 2023-07-19 09:57

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogtag_blog_authorinfo_blog_device_blog_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slider_poster',
            field=models.ImageField(default=1, upload_to=blog.models.SliderPosterPath),
            preserve_default=False,
        ),
    ]
