# Generated by Django 4.2.3 on 2023-07-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Importants/')),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Generally',
                'verbose_name_plural': 'Generally',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField()),
                ('meta_descriptions', models.TextField()),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LandingPage',
                'verbose_name_plural': 'Landing Page',
            },
        ),
    ]
