# Generated by Django 4.2.3 on 2023-07-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_generally_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generally',
            name='icon',
            field=models.ImageField(default=1, upload_to='Importants/'),
            preserve_default=False,
        ),
    ]
