# Generated by Django 4.2.3 on 2023-07-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_generally_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
