# Generated by Django 4.2.3 on 2023-07-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_landingpage_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generally',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
