# Generated by Django 4.2.3 on 2023-07-19 03:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Author',
            },
        ),
        migrations.CreateModel(
            name='AuthorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs', models.IntegerField(default=0)),
                ('note', ckeditor.fields.RichTextField()),
                ('Author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
            options={
                'verbose_name': 'Reports',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('Author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
            options={
                'verbose_name': 'Informations',
                'verbose_name_plural': 'Informations',
            },
        ),
    ]
